version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py shell -c 'from News_app.beat_setup import scraper_beat_task; scraper_beat_task()' &&
            gunicorn TechNews_project.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7

  worker:
    build: .
    command: celery -A TechNews_project worker --loglevel=info
    entrypoint: /app/entrypoint-celery.sh
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis

  beat:
    build: .
    command: celery -A TechNews_project beat --loglevel=info
    entrypoint: /app/entrypoint-celery.sh
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis

  flower:
    build: .
    command: celery -A TechNews_project flower --port=5555
    entrypoint: /app/entrypoint-celery.sh
    ports:
      - "5555:5555"
    env_file: .env
    depends_on:
      - redis

volumes:
  postgres_data: