# Generated by Django 5.2.4 on 2025-07-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_app', '0002_remove_newsitem_source_newsitem_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
