# Generated by Django 5.2.4 on 2025-07-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News_app', '0003_alter_source_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={},
        ),
    ]
