# Generated by Django 5.2.4 on 2025-07-23 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_app', '0004_alter_newsitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='source',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='News_app.source'),
        ),
    ]
